[package]
name = "fdk-aac"
version = "0.0.0"
authors = ["Charlie Somerville <charlie@charlie.bz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fdk-aac-sys = { version = "0.0.0", path = "fdk-aac-sys" }
